apiVersion: v1
kind: Service
metadata:
  name:  vprocache01
spec:
  selector:
    app:  vpromc
  type:  ClusterIP
  ports:
    - port:  11211 # the service would be accessed through this port 
      targetPort:  vpromc-port #and redirected to the deployment port
      protocol: TCP