#Database deployment definition file 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels: 
    app: vprodb
spec:
  selector: 
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: name
          image: vprofile/vprofiledb #already containerized image 
          volumeMounts:
            - name:  vpro-db-data
              mountPath:  /var/lib/mysql
          ports: # specifies the container port to connect to 
            - name: vprodb-port
              containerPort: 3306
          env:  #define your environment veriables and specify the ones from the secret file too 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-1a # This ensures that the databse is scheduled only in a node with this same label 
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore: 
            volumeID: vol-02cfef0e862b39268
            fsType: ext4
      initContainers: #This container is used to remove the lost+found folder from the mysql db before the main pod runs
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts: #You definitely have to mount the already created volume it'd work with and specify the mountpath
            - name: vpro-db-data
              mountPath: /var/lib/mysql

